server:
  port: 9090

management:
  endpoint:
    gateway:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
          - loggers
          - health
          - prometheus
          - info
          - gateway
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: classifieds
          uri: lb://CLASSIFIEDS
          predicates:
            - Path=/classifieds/**
        - id: ratings
          uri: lb://RATINGS
          predicates:
            - Path=/ratings/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



